[tool.poetry]
name = "hyperfocus-agent"
version = "0.1.0"
description = ""
authors = ["Brandon Bakker <brandon@bdmd.com.au>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
openai = "^2.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hyperfocus = "hyperfocus_agent.main:main"
